print('He said "I wont\'t come"')
print("I bought " + str(5)  + "Bycycle" )
print("I bought " + str(5)  + " Bycycle" )
print(" I bought " + str(6+2) + " Bycycle")
print("Hello:John".split(":"))
print("Hello:John:word".split(":"))
print("My Name is "+ "Hello:John:word".split(":")[1])